/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 medical.gltf --transform
Author: Miguel Adão (https://sketchfab.com/theauditor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medical-supplies-collection-eae9fc470e674c458791cf00b892340f
Title: Medical Supplies Collection
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const medicalImg = `${process.env.PUBLIC_URL}/assets/3D/medical-transformed.glb`;
  const { nodes, materials } = useGLTF(medicalImg);
  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.36, 0, 0]}>
          <mesh geometry={nodes.Top_Needles1_0.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Base_Needles1_0.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Top_Needles1_0_1.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Base_Needles1_0_1.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Top_Needles1_0_2.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Base_Needles1_0_2.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Top_Needles1_0_3.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Base_Needles1_0_3.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Top_Needles1_0_4.geometry} material={materials.Needles1} />
          <mesh geometry={nodes.Base_Needles1_0_4.geometry} material={materials.Needles1} />
        </group>
        <group position={[-0.36, 0, 0]}>
          <mesh geometry={nodes.Vaccine_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Liquid_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Vaccine1_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Liquid_Vaccines1_0_1.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Vaccine2_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Liquid_Vaccines1_0_2.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Vaccine3_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Liquid_Vaccines1_0_3.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Vaccine4_Vaccines1_0.geometry} material={materials.Vaccines1} />
          <mesh geometry={nodes.Liquid_Vaccines1_0_4.geometry} material={materials.Vaccines1} />
        </group>
        <group position={[2.73, 1.23, 0]} scale={[3, 2, 5]}>
          <group position={[-0.91, -0.46, 0]} scale={[0.33, 0.5, 0.2]}>
            <mesh geometry={nodes.Glove_Gloves_0.geometry} material={materials.Gloves} />
            <mesh geometry={nodes.Glove1_Gloves_0.geometry} material={materials.Gloves} />
            <mesh geometry={nodes.Glove2_Gloves_0.geometry} material={materials.Gloves} />
          </group>
          <mesh geometry={nodes.GlovesPack_Gloves_0.geometry} material={materials.Gloves} />
          <mesh geometry={nodes.Base_Gloves_0.geometry} material={materials.Gloves} position={[-0.01, 0.36, 0]} scale={[0.76, 1.14, 0.94]} />
        </group>
        <mesh geometry={nodes.Tray_Tray1_0.geometry} material={materials.Tray1} />
        <group position={[0, 15.28, 8.01]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Holder_Medkit_0.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor_Medkit_0.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor1_Medkit_0.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor_Medkit_0_1.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor1_Medkit_0_1.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor_Medkit_0_2.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Scisor2_Medkit_0.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Lock_Medkit_0.geometry} material={materials.Medkit} />
          <mesh geometry={nodes.Top_Medkit_0.geometry} material={materials.Medkit} />
        </group>
        <mesh geometry={nodes.Base_Medkit_0.geometry} material={materials.Medkit} />
        <mesh geometry={nodes.Needle_Line_Line2_0.geometry} material={materials.Line2} />
        <mesh geometry={nodes.Needle_Line2_0.geometry} material={materials.Line2} />
        <mesh geometry={nodes.Needle_Line_Line2_0_1.geometry} material={materials.Line2} />
        <mesh geometry={nodes.Needle_Line2_0_1.geometry} material={materials.Line2} />
        <mesh geometry={nodes.Bandage_Bandages1_0.geometry} material={materials.Bandages1} />
        <mesh geometry={nodes.Bandage1_Bandages1_0.geometry} material={materials.Bandages1} />
        <mesh geometry={nodes.Bandage2_Bandages1_0.geometry} material={materials.Bandages1} />
        <mesh geometry={nodes.Pill11_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill9_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill8_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill7_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill6_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill5_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill4_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill3_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill2_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill1_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCase_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCaseCover_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill16_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill15_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill14_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill13_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill12_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill11_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill10_PillsCase3_0.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill9_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill8_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill7_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill6_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill5_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill4_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill3_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill2_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill1_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCase_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCaseCover_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill16_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill15_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill14_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill13_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill12_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill11_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill10_PillsCase3_0_1.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill9_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill8_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill7_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill6_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill5_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill4_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill3_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill2_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill1_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Pill_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCase_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.PillsCaseCover_PillsCase3_0_2.geometry} material={materials.PillsCase3} />
        <mesh geometry={nodes.Patch_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch10_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch9_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch8_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch7_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch6_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch5_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch4_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch3_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch2_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch1_Patches1_0.geometry} material={materials.Patches1} position={[0, 0.04, 0]} />
        <mesh geometry={nodes.Patch11_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch12_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch13_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch14_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch15_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Patch_Box_Patches1_0.geometry} material={materials.Patches1} />
        <mesh geometry={nodes.Pills10_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills9_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills8_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills7_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills6_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills11_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills5_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills4_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills3_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills2_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Pills1_Pills0_0.geometry} material={materials.Pills0} />
        <mesh geometry={nodes.Thermometer_Thermometer1_0.geometry} material={materials.Thermometer1} />
        <mesh geometry={nodes.Spray_Spray1_0.geometry} material={materials.Spray1} />
        <mesh geometry={nodes.Spray_Trigger_Spray1_0.geometry} material={materials.Spray1} />
        <mesh geometry={nodes.Tubes_Supporter_Tubes1_0.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Cork_Tubes1_0.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Flask_Tubes1_0.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Liquid_Tubes1_0.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Cork_Tubes1_0_1.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Flask_Tubes1_0_1.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Liquid_Tubes1_0_1.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Cork_Tubes1_0_2.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Flask_Tubes1_0_2.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Liquid_Tubes1_0_2.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Cork_Tubes1_0_3.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Flask_Tubes1_0_3.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Liquid_Tubes1_0_3.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Cork_Tubes1_0_4.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Flask_Tubes1_0_4.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Liquid_Tubes1_0_4.geometry} material={materials.Tubes1} />
        <mesh geometry={nodes.Bust_Stethoscope1_0.geometry} material={materials.Stethoscope1} />
        <mesh geometry={nodes.Stethoscope_Stethoscope1_0.geometry} material={materials.Stethoscope1} />
        <mesh geometry={nodes.Blood_Bag_Blood_Bag1_0.geometry} material={materials.Blood_Bag1} />
        <mesh geometry={nodes.Blood_Blood_Bag1_0.geometry} material={materials.Blood_Bag1} position={[-0.39, 0.14, 0.15]} scale={[0.96, 0.83, 0.96]} />
        <mesh geometry={nodes.Mask_Mask1_0.geometry} material={materials.Mask1} />
      </group>
    </group>
  )
}

useGLTF.preload('/medical-transformed.glb')
